exports.seed = function(knex, promise) {
  return knex("stories").insert([
    {
      title: "Title: Scraps of Life",
      contents: `Look around.                    Off in one corner is a hand-dug latrine, just an open pit surrounded by a piece of blue plastic flapping in the wind. Everyone uses it.                    The center of activity is a black plastic hose that comes out of the ground, connected to a spigot. It is the only source of water here.                    “We don’t know where it comes from, but we drink it, we bathe in it and we cook with it,” one man says. “The kids have diarrhea most of thetime.”                    Kids play everywhere. Most of them are filthy. Almost everyone wears plastic sandals, though some of the kids are barefoot. Virtually everyone has cuts or scabs on their fingers and toes. Snow will be coming soon, and nobody here has warm clothes or boots.                    Over there, next to a 20-foot-high pile of scrap metal, a new tentis taking shape. It has an uneven dirt floor and a flimsy frame of nailed-together 1-by-4 boards. The walls are a ratty orange tarp, and the roof is covered with a second layer of dirty clear plastic.                    “There is no place else to go,” says the man building it, a father of four small children who fled the shelling in his home town of Homs a few weeks ago. “We don’t have money, clothes, nothing. I just left with my children. I had $500, but I spent it to get here.”                No one here wants to be identified by name. Most are brand-new arrivals, and the fear of war is still fresh. They are scared of retribution from President Bashar al-Assad’s government if they are identified publicly.                    The father from Homs ran a clothing store and lived a comfortable middle-class life before his house was destroyed. He fled to Lebanon and ended up here.                    “We’ve all had a shock,” he says. “We don’t even feel like we’re awake. I ask myself if we’re really here.”                    While he builds his tent, his family is bunking in the tent of another man who came here six weeks ago after his parents, his three brothers, his wife and their 1-year-old son were wiped out in a government bombing in Homs.                    “I can’t find a job here,” he says with a hollow look in his eyes. “Ican’t do anything. But these people helped me.”
                    Over by the water hose, a woman stands holding her 3-year-old daughter in her arms. The little girl has ugly burn scars up and down her right arm from a bomb attack on their house in Homs.                    The mother is now nine months pregnant, with a huge bump under her long purple robe. She says she has no idea where she will deliver the baby. She shrugs and says maybe she will just end up having the baby on the carpeted dirt floor of her tent.                    Outside the camp gate, which is just a hole in the corrugated metal fence, Ahmed Bougi, a big Lebanese man in a crew cut and a sweatsuit, says his family owns the lot, plus another one across the road where another 50 Syrians live. He says he cleared away the junk cars and opened the place to refugees three months ago.                    “They make it hard for me to collect,” he says. “Some of them don’t pay. But what can I do? Kick them out? I feel sorry for them. They have families.”                    He says he never considered letting the refugees have the land for free. He wants his rent.`,
      pending: 0
    },
    {
      title: "War Widow",
      contents: `She remembers telling him: “I don’t want to lose you. I don’t want my kids to grow up without a father.”                    She said she would leave him if he insisted, which they both knew was an empty threat. They had known each other since they were babies. They married when she was 18, on Sept. 1, 2000.                    She loved him, and as much as she loathed the regime of President Bashar al-Assad, she did not want him to pick up a gun and join therevolution.                    “He told me, ‘I will give my soul to my country, and I will leave my kids to God,’ ” she says. “Nobody could change his mind.”                    In a firefight on Feb. 25, 2012, Assad’s forces put a bullet through the heart of her husband, he, who worked in his father-in-law’s appliance shop before the war.
        After they buried him, his three brothers told their father to take the women and children to safety in Turkey. They would stay and fight with the Free Syrian Army.                    So the family started walking. They walked for three nights, lying low in fields during the day to avoid Assad’s forces. They hitched rides in the back of passing trucks, crouching low as shells fell nearby.                    “No words can express what I was feeling,”                    “I lost my husband. My kids lost their father. We were going to an uncertain future, and I couldn’t stand it.”                    Eventually they crossed the border and started a new life in the Oncupinar camp, near the border town of Kilis, one of 21 camps run by the Turkish government, which has spent more than $2.5 billion on housing, food, medical care and education for nearly 700,000 Syrian refugees.                    The camp opened in 2011 and covers 86 acres directly on the Syrian border. About 14,000 refugees live here in more than 2,000 prefabricated metal trailers — neat white boxes lined up in vast, straight rows along paved streets.                    The containers are about 22 feet wide by 9 feet deep. Inside, two small rooms, each with a window, are separated by a bathroom. They have built-in heaters/air conditioners, and most have a small sink, refrigerator and hot plate. White and blue plastic tarps cover most, helping with the relentless sun in the summer and the rains in the winter.                    The minarets of two mosques tower over a health clinic and three schools: the Olive Kindergarten, Peace Middle School and Freedom High School. Residents shop at several well-stocked grocery stores, using about $55 a month per person in food vouchers supplied by the Turkish government and the U.N. World Food Program.                    Fifteen members of the family share two trailers, sleeping on mats they roll up at night. A photo of Imad is taped to the wall in the room where Huda Khalaf sleeps with Imad’s parents and her children, ages 5, 7, 11and 12. There are no decorations.                    She wears a traditional long black robe as her children crowd in around her. She worries about Imad’s three brothers who are still fighting. She has already suffered two losses, including her 23-year-old brother, another Free Syrian Army fighter who was killed.                    Her husband was the first one buried in her village.                    “I am so proud,” she says.                    She still wears her gold wedding band.`,
      pending: 0
    },
    {
      title: "Lifestyle Lost",
      contents: `Before the war, his family was part of Syria’s elite. While the countryside waslargely agricultural and poor, the cities of Damascus and Aleppo were home to business leaders, doctors, lawyers and other professionals, many of whomwere fantastically wealthy.                    Bombs and artillery shells are equally lethal to rich and poor, and among the more than 2.3 million Syrian refugees are many wealthy Syrians who have had family slaughtered.                    “You don’t appreciate all that you have until it’s gone,” says a man, who had a thriving plastic-surgery practice in Aleppo, doing nose jobs and breast enhancements and reductions for wealthy clients from all over the world who came for what he calls “Chinese prices and European quality.”                    He knows that poorer refugees face more dire situations, but he says his losses are no less painful. He has enough savings left to support his family for another year, maybe a little more, but he worries about what he will do when the money runs out.                    He says he has not been able to work in Lebanon as a doctor, because of extremely high fees required to register as a foreign doctor.                    “We do appreciate this country for allowing us to stay. But what is the point of being able to stay if we can’t have any income?” he says. “I want to work. But I was told I would have to pay $300,000 to work as a doctor here.”                    He left Syria 18 months ago and moved to an apartment in Beirut, where his rent was $1,500 a month and Lana attended a private school that cost $10,000 a year. Since they moved to their new suburban apartment and a new school, they have cut those costs in half.                    Faham got his medical degree in London and speaks perfect English. He and his wife, Nourhan Haidar, a pharmacist, cheerfully offer guests tea and sweets amid the golden-trimmed furniture that came with their apartment. But Faham’s bright eyes turn sad and dark when he talks about the future.
                    “My friends in England who I studied with, they have private jets. I am living here. I have nothing. I have no security for my children,” he says. “Suddenly you find yourself out of work, and you have no faith in the future.”                    He home in Aleppo, a six-bedroom place worth $2 million, has been taken over by government forces. His weekend ranch, where he used toentertain the French and Turkish ambassadors around the swimming pool, has been badly damaged in the fighting and is abandoned.                    “If you wanted to sell it now for $1,000, nobody would buy it,” he says.                    His surgical clinic is closed, and his brother and his family have been living there since their house was destroyed. “My beautiful operating room has been turned into his kitchen,” he says, adding that he had to sell six of his seven cars to raise some quick cash to bring to Lebanon.                    Faham says the wealthy who stayed behind in Syria have become easy marks for kidnappers trying to raise money for their fight, both from the government and the rebels. He says that within the past few days an orthopedic-surgeon friend of his was kidnapped and his family paid a $100,000 ransom.                    Three prominent Syrian doctors he knows have lost families on refugee boats that have sunk in the Mediterranean off the Italian island of Lampedusa while trying to reach Europe. He just spoke to a neurosurgeon friend who paid smugglers $15,000 to get his family to Europe on one of the boats, then watched his twin sons and his wife drown when it sank.                    “Every country in the world interferes in Syria,” he says, “and nobody takes care of the Syrian people’s humanity and dignity.”`,
      pending: 0
    }
  ]);
};
